### ISSUE TITLE
Code changes are not  reflecting at supermarket 

### ISSUE THREAD

**Issue by sunilvishvakarma** [davidnewman/chef_kubectl#2]
David, 

The code changes which we made is not reflecting on the supermarket,  I think you need to bump up the version and push it to the supermarket.

Regards
Sunil

**Comment by davidnewman** [comment]
Yup. I’ll do that when I get a chance if you need it before then, you can just push it to your own chef server.

**Comment by sunilvishvakarma** [comment]
sure, thank you

**Comment by patoarvizu** [comment]
Any chance this will get pushed to the Supermarket soon? I'm running chef-solo, so pushing to my own server is not an option.

Thanks!

**Comment by davidnewman** [comment]
OK, 0.1.2 should be up now.
